import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");
const imageSize = width * 0.12; // 12% of screen width

export const styles = StyleSheet.create({
  container: { flex: 1, padding: 20 },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#76088b",
    flex: 1,
    textAlign: "center",
  },
  addTaskButton: {
    backgroundColor: "#9a12b6",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  addTaskButtonText: {
    color: "white",
    fontSize: 14,
    fontWeight: "600",
  },
  emptyState: { flex: 1, justifyContent: "center", alignItems: "center" },
  emptyText: { fontSize: 16, color: "gray", marginBottom: 20 },
  taskRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: "#76088b",
    borderRadius: 10,
    backgroundColor: "white",
  },
  highlightedTask: {
    borderColor: "#ff6b6b",
    borderWidth: 3,
    shadowColor: "#ff6b6b",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 5,
  },
  taskText: {
    fontSize: 20,
    fontWeight: "600",
    flex: 1,
  },
  taskImage: {
    width: 50,
    height: 50,
    marginRight: 12,
    borderRadius: 8,
  },
  iconContainer: {
    flexDirection: "row",
    gap: 15,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  modalContent: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 8,
    width: "80%",
  },
  editModalContent: {
    backgroundColor: "white",
    padding: 24,
    borderRadius: 12,
    width: "90%",
    maxHeight: "90%",
  },
  modalTitle: { fontSize: 18, fontWeight: "bold", marginBottom: 10 },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    padding: 10,
    marginBottom: 15,
  },
  imagePlaceholder: {
    height: 80,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    marginBottom: 15,
    position: "relative",
  },
  editImagePlaceholder: {
    height: 200,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    marginBottom: 15,
    position: "relative",
    backgroundColor: "#f9f9f9",
  },
  imagePreviewContainer: {
    position: "relative",
    width: "100%",
    height: "100%",
  },
  imagePreview: {
    width: "100%",
    height: "100%",
    borderRadius: 5,
  },
  editImagePreview: {
    width: "100%",
    height: "100%",
    borderRadius: 8,
    resizeMode: "cover",
  },
  imageActionsContainer: {
    position: "absolute",
    top: 8,
    right: 8,
    flexDirection: "row",
    gap: 8,
  },
  imageActionButton: {
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 20,
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  placeholderText: {
    color: "gray",
    fontSize: 14,
    marginTop: 8,
  },
  modalButtons: { flexDirection: "row", justifyContent: "space-between" },
  congratsOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
  },
  congratsContent: {
    backgroundColor: "white",
    padding: 30,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  congratsEmoji: {
    fontSize: 60,
    marginBottom: 20,
  },
  congratsText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#76088b",
  },
  titleContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  headerImage: {
    width: imageSize,
    height: imageSize,
    borderRadius: imageSize / 2, // for circular, or keep as imageSize * 0.2
    marginRight: 8,
  },
  editImageButton: {
    padding: 4,
  },
  removeImageButton: {
    backgroundColor: "#ff4444",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    marginBottom: 15,
  },
  removeImageText: {
    color: "white",
    fontWeight: "600",
  },
  titleContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  headerImage: {
    width: 40,
    height: 40,
    borderRadius: 8,
    marginRight: 8,
    marginTop: 16,
  },
  editImageButton: {
    padding: 4,
  },
  removeImageButton: {
    backgroundColor: "#ff4444",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    marginBottom: 15,
  },
  removeImageText: {
    color: "white",
    fontWeight: "600",
  },
  disabledTask: {
    backgroundColor: "#f0f0f0",
    opacity: 0.6,
  },
  disabledTaskText: {
    color: "#999",
    textDecorationLine: "line-through",
  },
  disabledIconContainer: {
    marginRight: 8,
  },
  cancelIconContainer: {
    marginRight: 8,
  },
  submitButton: {
    backgroundColor: "#4CAF50",
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 20,
    marginBottom: 20,
  },
  submitButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  leftContainer: {
    width: 50,
    alignItems: "flex-start",
  },
  rightContainer: {
    width: 90,
    alignItems: "flex-end",
    paddingTop: 16,
    paddingRight: 2,
  },
  backButtonLeft: {
    padding: 8,
  },
  savedTaskRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    backgroundColor: "#fff",
  },
  savedTaskImage: {
    width: 40,
    height: 40,
    borderRadius: 6,
    marginRight: 12,
  },
  savedTaskText: {
    flex: 1,
    fontSize: 16,
    fontWeight: "500",
  },
  savedTaskButtons: {
    flexDirection: "row",
    gap: 8,
  },
  savedTaskAddButton: {
    backgroundColor: "#4CAF50",
    padding: 8,
    borderRadius: 6,
  },
  savedTaskDeleteButton: {
    backgroundColor: "#ff4444",
    padding: 8,
    borderRadius: 6,
  },
});
